version: '3.1'

services:

  nginx:
    image: dagman62/nginx
    container_name: nginx
    ports:
      - "80:80" 
    volumes:
      - ./jenkins.conf:/etc/nginx/conf.d/default.conf
  jenkins:
    image: jenkins
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
